name: Deploy Java Backend to Plesk

on:
  push:
    branches:
      - main # yoki siz foydalanadigan branch nomi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonlash
        uses: actions/checkout@v2

      - name: Java o'rnatish
        uses: actions/setup-java@v2
        with:
          java-version: '17' # loyihangizga mos Java versiyasini tanlang
          distribution: 'temurin'

      - name: Loyihani yig'ish (build)
        run: |
          chmod +x ./mvnw
          ./mvnw clean package

      - name: JAR faylni Plesk'ga yuklash
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.PLESK_HOST }}
          username: ${{ secrets.PLESK_USERNAME }}
          password: ${{ secrets.PLESK_PASSWORD }}
          source: "target/spring-security.jar" # Yig'ilgan JAR fayl manzili
          target: "/var/www/vhosts/bnav.uz/back.bnav.uz" # Maqsadli katalog