name: Serverga joylashtirish (Deploy)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1-qadam: Repositoryni tekshirib chiqish (checkout)
    - name: Kodni tekshirib chiqish
      uses: actions/checkout@v2

    # 2-qadam: SSH kalitini sozlash
    - name: SSH sozlash
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 3-qadam: Serverni known_hosts fayliga qo'shish (SSH'ning xavfsizligini tekshirishdan qochish)
    - name: Serverni known_hosts ga qo'shish
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 162.55.182.148 >> ~/.ssh/known_hosts

    # 4-qadam: Kodingizni serverga joylashtirish
    - name: Kodni joylashtirish
      run: |
        ssh -o StrictHostKeyChecking=no root@162.55.182.148 "cd /path/to/your/project && git pull && ./deploy.sh"
