name: Deploy Java Backend to Plesk

on:
  push:
    branches:
      - main # yoki siz foydalanadigan branch nomi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonlash
        uses: actions/checkout@v2

      - name: Java o'rnatish
        uses: actions/setup-java@v2
        with:
          java-version: '17' # loyihangizga mos Java versiyasini tanlang
    

      - name: Loyihani yig'ish (build)
        run: |
          ./mvnw clean package

      - name: JAR faylni Plesk'ga yuklash
        uses: appleboy/scp-action@v0.1.0
        with:
          host: 37.27.181.70
          username: bnav.uz_website1995888
          password: aQL3yzK2#112iesad
          source: "target/spring-security.jar" # Yig'ilgan JAR fayl manzili
          target: "/var/www/vhosts/bnav.uz/back.bnav.uz" #
