name: Deploy Spring Boot Project

on:
  push:
    branches:
      - main  # yoki boshqa asosiy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Kodingizni tekshirish
      uses: actions/checkout@v2

    - name: SSH Private Keyni yaratish
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH ruxsatlarini o‘rnatish
      run: chmod 600 ~/.ssh/id_rsa

    - name: Host key verificationni o‘tkazib yuborish
      run: |
        mkdir -p ~/.ssh
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

    - name: Serverda git pull qilish (Agar loyihangiz mavjud bo'lsa)
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@162.55.182.148 'cd /home/root/deploy/optimitBackend && git pull origin main'

    - name: Maven build qilish
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@162.55.182.148 'cd /home/root/deploy/optimitBackend && mvn clean package -DskipTests'

    - name: Deploy qilish
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@162.55.182.148 '
          JAR_PATH="/home/root/deploy/optimitBackend/target/spring-security.jar"
          PID=$(pgrep -f $JAR_PATH)
          
          # Agar jar fayl ishlayotgan bo‘lsa, uni to‘xtatish
          if [ -n "$PID" ]; then
            echo "Stopping existing jar process..."
            kill -9 $PID
          fi

          # Yangi jar faylni ishga tushirish
          echo "Starting new jar process..."
          nohup java -jar $JAR_PATH > /dev/null 2>&1 &
          echo "Application deployed successfully."
        '
