name: Spring Boot Loyihasini Serverga Deploy Qilish

on:
  push:
    branches:
      - main  # yoki boshqa asosiy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Kodingizni tekshirish
      uses: actions/checkout@v2

    - name: Serverda deploy papkasini yaratish
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} root@162.55.182.148 'mkdir -p /home/root/deploy'

    - name: Serverga deploy qilish
      run: |
        scp -i ${{ secrets.SSH_PRIVATE_KEY }} target/spring-security.jar root@162.55.182.148:/home/root/deploy
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} root@162.55.182.148 'bash -s' < ./deploy-script.sh
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
