name: Deploy Spring Boot Project

on:
  push:
    branches:
      - main  # yoki boshqa asosiy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Kodingizni tekshirish
      uses: actions/checkout@v2

    - name: SSH Private Keyni yaratish
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH ruxsatlarini o‘rnatish
      run: chmod 600 ~/.ssh/id_rsa

    - name: Host key verificationni o‘tkazib yuborish
      run: |
        mkdir -p ~/.ssh
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

    - name: Serverda papka yaratish
      run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@162.55.182.148 'mkdir -p /home/root/deploy'

    - name: Deploy qilish
      run: |
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no target/spring-security.jar root@162.55.182.148:/home/root/deploy
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@162.55.182.148 'bash -s' < ./deploy-script.sh
 
